### ISSUE TITLE
type '(String) => Future<Null>' is not a subtype of type '(dynamic) => void'

### ISSUE THREAD

**Issue by amangautam1** [ianldgs/material_search#24]
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (17186): The following assertion was thrown while handling a gesture:
I/flutter (17186): type '(String) => Future<Null>' is not a subtype of type '(dynamic) => void'
I/flutter (17186): 
I/flutter (17186): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17186): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17186): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17186):   https://github.com/flutter/flutter/issues/new
I/flutter (17186): 
I/flutter (17186): When the exception was thrown, this was the stack:
I/flutter (17186): #0      _MaterialSearchState.build.<anonymous closure>.<anonymous closure> (package:material_search/material_search.dart)
I/flutter (17186): #1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter (17186): #2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter (17186): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (17186): #4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (17186): #5      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter (17186): #6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (17186): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (17186): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (17186): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (17186): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (17186): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (17186): #12     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (17186): #13     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

**Comment by ianldgs** [comment]
Hello @amangautam1,
Can you post the code that lead to this exception?

**Comment by amangautam1** [comment]
I have a list of song. I am getting the value of **selected** as the text I search for. But for onSubmit, I didn't get any value.
class SearchSong extends StatefulWidget {
  List<Song> songs;
  SearchSong(this.songs);
  @override
  State<StatefulWidget> createState() {
    return new _statesearch();
  }
}

class _statesearch extends State<SearchSong> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        body: new SafeArea(
      child: new MaterialSearch<String>(
        placeholder: 'Search songs', //placeholder of the search bar text input
        results: widget.songs
            .map((song) => new MaterialSearchResult<String>(
                  value: song.title, //The value must be of type <String>
                  text: song.title, //String that will be show in the list
                  icon: Icons.music_note,
                ))
            .toList(),

        onSelect: (String selected) async {
          if (selected == null) {
            return;
          }
          print(selected);
        },
        onSubmit: (String value){
          print(value);
          
        },
      ),
    ));
  }
}

**Comment by ianldgs** [comment]
Try to change the `onSelect` to (dynamic selected) *not async* { ... }.
If you need to do something async, just call the method inside `onSelect` without awaiting.
Le me know if it works for you!

**Comment by amangautam1** [comment]
Thanks ianldgs , it solved the problem.

**Comment by wujun** [comment]
@ianldgs Thanks a lot ! great jobs
