### ISSUE TITLE
Question - Back Button on main search page?

### ISSUE THREAD

**Issue by samgithub-duplicate** [ianldgs/material_search#25]
This is more a question than an issue. -- Any suggestions will be appreciated.
Is there a way to include a 'back' arrow on the page "Material Search Demo" (MSD)

I am arriving at the search page from Another page (MSD is not my main home page).  

Right now I can do this only by using the phone's back button.  Is this possible with "material_search"

Thanks.

**Comment by ianldgs** [comment]
You can put a `new BackButton()` on the `leading` property of the `AppBar`.
