### ISSUE TITLE
less results when keyboard up

### ISSUE THREAD

**Issue by RobertBrunhage** [ianldgs/material_search#26]
Hey!

When I first navigate to my screen with the search bar it shows the full list on the screen. As soon as I press on the search field and the keyboard comes up it removes a lot of the results and only shows 3 even though there is a lot of space left between the keyboard and the results.

![image](https://user-images.githubusercontent.com/26344867/42153030-3584a3ee-7de2-11e8-8c76-af9ef067a5dd.png)

![image](https://user-images.githubusercontent.com/26344867/42153119-6c7722c8-7de2-11e8-9b72-3556ea7ea3ab.png)

![image](https://user-images.githubusercontent.com/26344867/42153122-72a21a86-7de2-11e8-9677-9d8613c1886d.png)

Thanks for the awesome package!

**Comment by lidroider** [comment]
You shouldn't use MaterialSearch in Scaffold because MaterialSearch returned Scaffold.
Change to  `return new MaterialSearch`
Hope this to help you

**Comment by RobertBrunhage** [comment]
Changed it to return MaterialSearch but it made no difference. :/

**Comment by RobertBrunhage** [comment]
That resolved the issue I had, thanks!

**Comment by ianldgs** [comment]
Woow! Cool. I didn't have time to look in to it. Happy that @lidroider found the solution! Thanks!
