### ISSUE TITLE
How to navigate forth and back without losing searched text

### ISSUE THREAD

**Issue by jagdishjadeja** [ianldgs/material_search#36]
I want to search something
when search page show similar item then i want to navigate to new screen with selected search result
when i press back i want to go back to search page instead of main screen with searched text on search bar
and then again able click on another search result.
any suggestion on how can i do it ?

**Comment by ianldgs** [comment]
There is currently no way of doing this. It could be implemented as a new option, something like `persistent: true`

**Comment by jagdishjadeja** [comment]
Thanks for help
