### ISSUE TITLE
MaterialSearch not showing result on input change

### ISSUE THREAD

**Issue by nhanquach** [ianldgs/material_search#41]
Hi, thank you for this great package.

I am having an issue with the MaterialSearch as it **does not show the result** after the input is focused and the keyboard is popped up, typing something into the search also shows no result.

Notes:
- This does not happen with the MaterialSearchInput.
- When I tap Done or The arrow down to hide the keyboard, the results now showed.

Below is my code block related to this issue:
```
List _names = [
    'Igor Minar',
    'Brad Green',
    'Dave Geddes',
    'Naomi Black',
    'Greg Weber',
    'Dean Sofer',
    'Wes Alvaro',
    'John Scott',
    'Daniel Nadasi',
  ];

  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Form(
      key: _formKey,
      child: MaterialSearch<String>(
        placeholder: 'Search',
        results: _names
            .map((v) => MaterialSearchResult<String>(
                  icon: Icons.center_focus_weak,
                  value: v,
                  text: v,
                ))
            .toList(),
        onSelect: (dynamic value) => Navigator.of(context).pop(value),
      ),
    ));
  }
```

**Comment by lnalex** [comment]
Same issue..

**Comment by alxlion** [comment]
Duplicate https://github.com/ianldgs/material_search/issues/26

You need to get the MaterialSearch out of the Scaffold widget

**Comment by ianldgs** [comment]
@lnalex you are right. Forgot about that. @nhanquach check this and we will re-open if it still happening.
