### ISSUE TITLE
Crash if getResults isn't passed to function

### ISSUE THREAD

**Issue by parrotmac** [ianldgs/material_search#6]
It seems like failing to pass a `getResults` method to a `MaterialSearch<T>({...})` call will result in a crash once you start entering any input into the search box.

Code example:
```
new MaterialSearch<String>(
    placeholder: 'Search', //placeholder of the search bar text input
    results: _list.map((li) => new MaterialSearchResult<String>(
        value: li, //The value must be of type <String>
        text: li, //String that will be show in the list
    )).toList(),
    onSelect: onSelect: (String selected) => print
)
```

Error: `NoSuchMethodError: The method 'call' was called on null.`

I think the offending snippet is here: https://github.com/ianldgs/material_search/blob/2fc176db3bcf5defd98f1827e609d5dba48892a8/lib/material_search.dart#L113

For now a simple null-check seems to work, but I'm still trying to wrap my head around the whole of Flutter in general (been using if for less than a week), so I'm pretty uncertain on how it should behave. It looks like issue was introduced as part of the refactoring in fixing #3.

Here's what I'm using to workaround...does this seem usable?
```
var results = widget.results;
if(widget.getResults != null) {
    results = await widget.getResults(_criteria);
}
```
Also, as an aside, it looks like the `loading` option is no longer relevant, but it's still shown in the example in the Readme. 
Do you want me to submit a PR?

**Comment by ianldgs** [comment]
There is no need for a PR. I will fix that on the 0.2.0 release, that will come with some new features, like validation, formating and debounce for the getResults.
And your are right about the loading option.
